#!/bin/bash
#Wrap anvil to avoid the missing -D argument and call this script instead

#For the moment, you can avoid this however you prefer.
#I suggest just naming your tag directory "bin" and let the default amboso behaviour win... But this problem shall not go unsolved.
#TODO:
#I tought this might be a nice motivation to fix the problem in the tool

#Uncomment for trace
#AMBOSO_TRACING=1

if [[ $AMBOSO_TRACKING -gt 0 ]] ; then {

  printf "\033[1;33m[DEBUG]    Backtrace ON [\"set AMBOSO_TRACING=$AMBOSO_TRACING\"].\e[0m\n"

  ./amboso/amboso -D "./amboso-tags/" "$@"

} else {

  #printf "\033[1;36m[DEBUG]    !NO! Backtrace [\"set AMBOSO_TRACING=$AMBOSO_TRACING\"].\e[0m\n\n\033[1;35mTry uncommenting line 10 in \"anwrap\" to have some backtrace. Very WIP.\e[0m\n"


  ./amboso/amboso -D "./amboso-tags/" "$@"
}
fi
