name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: make

    - name: Build and check version
      run: make verscheck

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
